services:
  - type: web
    name: sotnur
    runtime: python
    repo: https://github.com/maxxmoto/sotnur
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_bkXZBLxcM9W0@ep-silent-grass-aqcheui1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: EMAIL_PASSWORD
        sync: false
